//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MiniSQL.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MiniSQLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IMiniSQLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] MiniSQLParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.simpleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleStatement([NotNull] MiniSQLParser.SimpleStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.quitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuitStatement([NotNull] MiniSQLParser.QuitStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.execFileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecFileStatement([NotNull] MiniSQLParser.ExecFileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.showTablesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShowTablesStatement([NotNull] MiniSQLParser.ShowTablesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.createStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateStatement([NotNull] MiniSQLParser.CreateStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.createTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateTable([NotNull] MiniSQLParser.CreateTableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.createIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateIndex([NotNull] MiniSQLParser.CreateIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.dropStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropStatement([NotNull] MiniSQLParser.DropStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.deleteStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteStatement([NotNull] MiniSQLParser.DeleteStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.insertStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsertStatement([NotNull] MiniSQLParser.InsertStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.selectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectStatement([NotNull] MiniSQLParser.SelectStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.queryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQueryExpression([NotNull] MiniSQLParser.QueryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.fromClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFromClause([NotNull] MiniSQLParser.FromClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.queryExpressionParens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQueryExpressionParens([NotNull] MiniSQLParser.QueryExpressionParensContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.dropIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropIndex([NotNull] MiniSQLParser.DropIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.dropTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropTable([NotNull] MiniSQLParser.DropTableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.insertValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsertValues([NotNull] MiniSQLParser.InsertValuesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.valueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueList([NotNull] MiniSQLParser.ValueListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>values</c>
	/// labeled alternative in <see cref="MiniSQLParser.exprexprexprexprexprexprexprexprexprexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValues([NotNull] MiniSQLParser.ValuesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.whereClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhereClause([NotNull] MiniSQLParser.WhereClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.tableElementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableElementList([NotNull] MiniSQLParser.TableElementListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.tableElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableElement([NotNull] MiniSQLParser.TableElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.tableConstraintDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableConstraintDef([NotNull] MiniSQLParser.TableConstraintDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.columnDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnDefinition([NotNull] MiniSQLParser.ColumnDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.fieldDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDefinition([NotNull] MiniSQLParser.FieldDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.dataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataType([NotNull] MiniSQLParser.DataTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.fieldLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldLength([NotNull] MiniSQLParser.FieldLengthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.columnAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnAttribute([NotNull] MiniSQLParser.ColumnAttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.createIndexTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateIndexTarget([NotNull] MiniSQLParser.CreateIndexTargetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.keyListVariants"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyListVariants([NotNull] MiniSQLParser.KeyListVariantsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.tableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableName([NotNull] MiniSQLParser.TableNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.columnName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnName([NotNull] MiniSQLParser.ColumnNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.keyPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyPart([NotNull] MiniSQLParser.KeyPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.indexRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexRef([NotNull] MiniSQLParser.IndexRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.tableRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableRef([NotNull] MiniSQLParser.TableRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.fieldIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldIdentifier([NotNull] MiniSQLParser.FieldIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.indexName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexName([NotNull] MiniSQLParser.IndexNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.pureIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPureIdentifier([NotNull] MiniSQLParser.PureIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] MiniSQLParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.qualifiedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedIdentifier([NotNull] MiniSQLParser.QualifiedIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprAtom</c>
	/// labeled alternative in <see cref="MiniSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprAtom([NotNull] MiniSQLParser.ExprAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprOr</c>
	/// labeled alternative in <see cref="MiniSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprOr([NotNull] MiniSQLParser.ExprOrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprNot</c>
	/// labeled alternative in <see cref="MiniSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprNot([NotNull] MiniSQLParser.ExprNotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprMul</c>
	/// labeled alternative in <see cref="MiniSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprMul([NotNull] MiniSQLParser.ExprMulContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprPar</c>
	/// labeled alternative in <see cref="MiniSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprPar([NotNull] MiniSQLParser.ExprParContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprAdd</c>
	/// labeled alternative in <see cref="MiniSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprAdd([NotNull] MiniSQLParser.ExprAddContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprAnd</c>
	/// labeled alternative in <see cref="MiniSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprAnd([NotNull] MiniSQLParser.ExprAndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprXor</c>
	/// labeled alternative in <see cref="MiniSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprXor([NotNull] MiniSQLParser.ExprXorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprSign</c>
	/// labeled alternative in <see cref="MiniSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprSign([NotNull] MiniSQLParser.ExprSignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprCompare</c>
	/// labeled alternative in <see cref="MiniSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprCompare([NotNull] MiniSQLParser.ExprCompareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompOp([NotNull] MiniSQLParser.CompOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] MiniSQLParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.scientific"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScientific([NotNull] MiniSQLParser.ScientificContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniSQLParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] MiniSQLParser.VariableContext context);
}
